"""update camera rtsp

Revision ID: 0034cd44926d
Revises: 17031e036ee1
Create Date: 2024-12-25 19:16:51.116330

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0034cd44926d"
down_revision: Union[str, None] = "17031e036ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("frames_storage")
    op.add_column("result", sa.Column("label", sa.JSON(), nullable=False))
    op.add_column("result", sa.Column("label_count", sa.JSON(), nullable=False))
    op.add_column("result", sa.Column("camera_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "result", "camera_rtsp", ["camera_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "result", type_="foreignkey")
    op.drop_column("result", "camera_id")
    op.drop_column("result", "label_count")
    op.drop_column("result", "label")
    op.create_table(
        "frames_storage",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("frame_data", sa.BLOB(), nullable=False),
        sa.Column("frame_time", mysql.DATETIME(), nullable=False),
        sa.Column(
            "camera_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("camera_status", mysql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
