"""update case

Revision ID: 3bf8d022c917
Revises: 9c600bf366ab
Create Date: 2024-12-16 15:22:27.495919

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bf8d022c917"
down_revision: Union[str, None] = "9c600bf366ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case", sa.Column("case_report", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("case", "case_report")
    # ### end Alembic commands ###
