"""update license

Revision ID: 8e495eddc578
Revises: df4cc068261f
Create Date: 2024-12-15 22:49:58.775762

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e495eddc578"
down_revision: Union[str, None] = "df4cc068261f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("license", sa.Column("start_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("license", "start_date")
    # ### end Alembic commands ###
