"""add user-limit-license

Revision ID: 951cb7287a55
Revises: b04bcf77f247
Create Date: 2024-12-13 19:34:55.370864

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "951cb7287a55"
down_revision: Union[str, None] = "b04bcf77f247"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "license", "expiry_date", existing_type=mysql.DATETIME(), nullable=False
    )
    op.drop_constraint("license_ibfk_2", "license", type_="foreignkey")
    op.drop_constraint("license_ibfk_1", "license", type_="foreignkey")
    op.drop_column("license", "limit_id")
    op.drop_column("license", "user_id")
    op.add_column(
        "license_limit_user", sa.Column("license_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "license_limit_user", sa.Column("limit_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "license_limit_user_ibfk_2", "license_limit_user", type_="foreignkey"
    )
    op.create_foreign_key(None, "license_limit_user", "limit", ["limit_id"], ["id"])
    op.create_foreign_key(None, "license_limit_user", "license", ["license_id"], ["id"])
    op.drop_column("license_limit_user", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "license_limit_user",
        sa.Column(
            "role_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "license_limit_user", type_="foreignkey")
    op.drop_constraint(None, "license_limit_user", type_="foreignkey")
    op.create_foreign_key(
        "license_limit_user_ibfk_2", "license_limit_user", "role", ["role_id"], ["id"]
    )
    op.drop_column("license_limit_user", "limit_id")
    op.drop_column("license_limit_user", "license_id")
    op.add_column(
        "license",
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "license",
        sa.Column(
            "limit_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key("license_ibfk_1", "license", "limit", ["limit_id"], ["id"])
    op.create_foreign_key("license_ibfk_2", "license", "user", ["user_id"], ["id"])
    op.alter_column(
        "license", "expiry_date", existing_type=mysql.DATETIME(), nullable=True
    )
    # ### end Alembic commands ###
