"""update case

Revision ID: 992312448f53
Revises: 3bf8d022c917
Create Date: 2024-12-16 17:53:51.815753

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "992312448f53"
down_revision: Union[str, None] = "3bf8d022c917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("case_camera_mapping")
    op.drop_index("ix_camera_id", table_name="camera")
    op.drop_table("camera")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "camera",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("nvr_id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("camera_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created_date", mysql.DATETIME(), nullable=False),
        sa.Column("updated_date", mysql.DATETIME(), nullable=False),
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "location_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], name="camera_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_camera_id", "camera", ["id"], unique=False)
    op.create_table(
        "case_camera_mapping",
        sa.Column(
            "case_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "camera_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["camera_id"], ["camera.id"], name="case_camera_mapping_ibfk_2"
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["case.id"], name="case_camera_mapping_ibfk_1"
        ),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
