"""update license

Revision ID: 9c600bf366ab
Revises: 8e495eddc578
Create Date: 2024-12-15 23:17:39.108240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9c600bf366ab"
down_revision: Union[str, None] = "8e495eddc578"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_license_mapping",
        sa.Column("license_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["license.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.drop_table("license_limit_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "license_limit_user",
        sa.Column(
            "license_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["license_id"], ["license.id"], name="license_limit_user_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="license_limit_user_ibfk_3"
        ),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.drop_table("user_license_mapping")
    # ### end Alembic commands ###
