"""update camera rtsp

Revision ID: 9e0c565297c7
Revises: a0d17a3a5fa5
Create Date: 2024-12-12 19:47:12.501166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9e0c565297c7"
down_revision: Union[str, None] = "a0d17a3a5fa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("camera_rtsp", "nvr_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "camera_rtsp", sa.Column("nvr_id", mysql.VARCHAR(length=255), nullable=False)
    )
    # ### end Alembic commands ###
