"""update camera rtsp

Revision ID: a63e2a743218
Revises: 992312448f53
Create Date: 2024-12-25 18:50:18.639168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a63e2a743218"
down_revision: Union[str, None] = "992312448f53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "result_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("result_type", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_result_type_id"), "result_type", ["id"], unique=False)
    op.add_column("result", sa.Column("result_type_id", sa.Integer(), nullable=True))
    op.add_column("result", sa.Column("label", sa.JSON(), nullable=False))
    op.add_column("result", sa.Column("label_count", sa.JSON(), nullable=False))
    op.add_column("result", sa.Column("camera_id", sa.Integer(), nullable=True))
    op.alter_column(
        "result", "frame_time", existing_type=mysql.DATETIME(), nullable=True
    )
    op.drop_index("ix_result_id", table_name="result")
    op.create_foreign_key(None, "result", "result_type", ["result_type_id"], ["id"])
    op.create_foreign_key(None, "result", "camera_rtsp", ["camera_id"], ["id"])
    op.drop_column("result", "similarity_score")
    op.drop_column("result", "threshold")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "result", sa.Column("threshold", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "result",
        sa.Column("similarity_score", mysql.VARCHAR(length=255), nullable=False),
    )
    op.drop_constraint(None, "result", type_="foreignkey")
    op.drop_constraint(None, "result", type_="foreignkey")
    op.create_index("ix_result_id", "result", ["id"], unique=False)
    op.alter_column(
        "result", "frame_time", existing_type=mysql.DATETIME(), nullable=False
    )
    op.drop_column("result", "camera_id")
    op.drop_column("result", "label_count")
    op.drop_column("result", "label")
    op.drop_column("result", "result_type_id")
    op.drop_index(op.f("ix_result_type_id"), table_name="result_type")
    op.drop_table("result_type")
    # ### end Alembic commands ###
