"""add license

Revision ID: b04bcf77f247
Revises: 9e0c565297c7
Create Date: 2024-12-13 13:18:15.243075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b04bcf77f247"
down_revision: Union[str, None] = "9e0c565297c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("result_manager_mapping")
    op.drop_constraint("user_ibfk_1", "user", type_="foreignkey")
    op.drop_column("user", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "company_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key("user_ibfk_1", "user", "company", ["company_id"], ["id"])
    op.create_table(
        "result_manager_mapping",
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "company_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name="result_manager_mapping_ibfk_2"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="result_manager_mapping_ibfk_1"
        ),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
