"""add seed data

Revision ID: b773d88ab06c
Revises: 0034cd44926d
Create Date: 2025-01-10 10:52:30.714536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b773d88ab06c"
down_revision: Union[str, None] = "0034cd44926d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("frames_storage")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frames_storage",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("frame_data", sa.BLOB(), nullable=False),
        sa.Column("frame_time", mysql.DATETIME(), nullable=False),
        sa.Column(
            "camera_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("camera_status", mysql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
