"""Describe your changes

Revision ID: df4cc068261f
Revises: ee24630bbe35
Create Date: 2024-12-15 21:24:16.241026

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "df4cc068261f"
down_revision: Union[str, None] = "ee24630bbe35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("license", sa.Column("limit_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "license", "limit", ["limit_id"], ["id"])
    op.drop_constraint(
        "license_limit_user_ibfk_2", "license_limit_user", type_="foreignkey"
    )
    op.drop_column("license_limit_user", "limit_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "license_limit_user",
        sa.Column(
            "limit_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "license_limit_user_ibfk_2", "license_limit_user", "limit", ["limit_id"], ["id"]
    )
    op.drop_constraint(None, "license", type_="foreignkey")
    op.drop_column("license", "limit_id")
    # ### end Alembic commands ###
