"""update license module

Revision ID: ee24630bbe35
Revises: 951cb7287a55
Create Date: 2024-12-13 22:39:19.091266

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ee24630bbe35"
down_revision: Union[str, None] = "951cb7287a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "license", "expiry_date", existing_type=mysql.DATETIME(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "license", "expiry_date", existing_type=mysql.DATETIME(), nullable=False
    )
    # ### end Alembic commands ###
