"""master_data

Revision ID: 4080be8a11eb
Revises: 
Create Date: 2025-01-10 13:27:44.962614

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from migrations.versions.data.master_data_4080be8a11eb import seed_master_data

# revision identifiers, used by Alembic.
revision: str = "4080be8a11eb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(length=255), nullable=False),
        sa.Column("case_name", sa.String(length=255), nullable=False),
        sa.Column("case_description", sa.String(length=255), nullable=True),
        sa.Column("case_status", sa.String(length=255), nullable=False),
        sa.Column("case_report", sa.String(length=255), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_index(op.f("ix_case_id"), "case", ["id"], unique=False)
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_email", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("company_description", sa.String(length=255), nullable=True),
        sa.Column("company_address", sa.String(length=255), nullable=False),
        sa.Column("company_pin_code", sa.String(length=255), nullable=False),
        sa.Column("company_website", sa.String(length=255), nullable=False),
        sa.Column("company_contact", sa.String(length=255), nullable=False),
        sa.Column("company_poc", sa.String(length=255), nullable=False),
        sa.Column("company_poc_contact", sa.String(length=255), nullable=False),
        sa.Column("company_status", sa.Boolean(), nullable=False),
        sa.Column("deployment_region", sa.String(length=255), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_id"), "company", ["id"], unique=False)
    op.create_table(
        "limit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("subtype", sa.String(length=255), nullable=False),
        sa.Column("current_limit", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.create_index(op.f("ix_limit_id"), "limit", ["id"], unique=False)
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_name", sa.String(length=255), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_location_id"), "location", ["id"], unique=False)
    op.create_table(
        "result_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("result_type", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_result_type_id"), "result_type", ["id"], unique=False)
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column("user_password", sa.String(length=255), nullable=False),
        sa.Column("user_status", sa.Boolean(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_user_email"), "user", ["user_email"], unique=True)
    op.create_table(
        "camera_rtsp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_name", sa.String(length=255), nullable=False),
        sa.Column("rtsp_url", sa.String(length=255), nullable=False),
        sa.Column("process_fps", sa.Integer(), nullable=False),
        sa.Column("is_tcp", sa.Boolean(), nullable=True),
        sa.Column("camera_resolution", sa.String(length=255), nullable=False),
        sa.Column("camera_ip", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_processing", sa.Boolean(), nullable=False),
        sa.Column("roi_type", sa.Boolean(), nullable=False),
        sa.Column("roi_url", sa.String(length=255), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_camera_rtsp_id"), "camera_rtsp", ["id"], unique=False)
    op.create_table(
        "company_setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=255), nullable=False),
        sa.Column("end_time", sa.String(length=255), nullable=False),
        sa.Column("buffer_time", sa.String(length=255), nullable=False),
        sa.Column("is_used_camera", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_setting_id"), "company_setting", ["id"], unique=False
    )
    op.create_table(
        "license",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("license_key", sa.String(length=255), nullable=True),
        sa.Column("key_status", sa.String(length=20), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("limit_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["limit_id"],
            ["limit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_license_id"), "license", ["id"], unique=False)
    op.create_index(
        op.f("ix_license_key_status"), "license", ["key_status"], unique=False
    )
    op.create_index(
        op.f("ix_license_license_key"), "license", ["license_key"], unique=False
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notification_message", sa.String(length=255), nullable=False),
        sa.Column("type_of_notification", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("is_unread", sa.Boolean(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_id"), "notification", ["id"], unique=False)
    op.create_table(
        "suspect",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("suspect_name", sa.String(length=255), nullable=False),
        sa.Column("suspect_image_path", sa.String(length=255), nullable=False),
        sa.Column("suspect_image_url", sa.String(length=255), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suspect_id"), "suspect", ["id"], unique=False)
    op.create_table(
        "user_location",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    op.create_table(
        "case_camera_rtsp_mapping",
        sa.Column("case_id", sa.Integer(), nullable=True),
        sa.Column("camera_rtsp_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camera_rtsp_id"],
            ["camera_rtsp.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case.id"],
        ),
    )
    op.create_table(
        "result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("file_url", sa.String(length=255), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=False),
        sa.Column("suspect_id", sa.Integer(), nullable=True),
        sa.Column("result_type_id", sa.Integer(), nullable=True),
        sa.Column("frame_time", sa.DateTime(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("updated_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("label", sa.JSON(), nullable=False),
        sa.Column("label_count", sa.JSON(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["camera_rtsp.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_type_id"],
            ["result_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suspect_id"],
            ["suspect.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_license_mapping",
        sa.Column("license_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["license.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    seed_master_data(op=op)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_license_mapping")
    op.drop_table("result")
    op.drop_table("case_camera_rtsp_mapping")
    op.drop_table("user_role")
    op.drop_table("user_location")
    op.drop_index(op.f("ix_suspect_id"), table_name="suspect")
    op.drop_table("suspect")
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_license_license_key"), table_name="license")
    op.drop_index(op.f("ix_license_key_status"), table_name="license")
    op.drop_index(op.f("ix_license_id"), table_name="license")
    op.drop_table("license")
    op.drop_index(op.f("ix_company_setting_id"), table_name="company_setting")
    op.drop_table("company_setting")
    op.drop_index(op.f("ix_camera_rtsp_id"), table_name="camera_rtsp")
    op.drop_table("camera_rtsp")
    op.drop_index(op.f("ix_user_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_result_type_id"), table_name="result_type")
    op.drop_table("result_type")
    op.drop_index(op.f("ix_location_id"), table_name="location")
    op.drop_table("location")
    op.drop_index(op.f("ix_limit_id"), table_name="limit")
    op.drop_table("limit")
    op.drop_index(op.f("ix_company_id"), table_name="company")
    op.drop_table("company")
    op.drop_index(op.f("ix_case_id"), table_name="case")
    op.drop_table("case")
    # ### end Alembic commands ###
